name: Docker CI

on:
  # Disabled cronjobs first until we configured the change detection logic.
  #schedule:
  #  - cron: '30 3 * * *'
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
    # TODO: use paths-filter action later
    paths:
      - "Dockerfile"
      - "vaultwarden-startup"
      - ".github/workflows/docker-ci.yml"
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: vaultwarden-paas-starter
  QUAYIO_NAMESPACE: ajhalili2006
  DOCKERHUB_NAMESPACE: Ajhalilidev06ph # TODO: Update this before I add Docker Hub login stuff.

jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # use GITHUB_TOKEN instead of my PAT for security reasons

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      # TODO: Also login to Quay and DockerHub
      - name: Authenicate to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3.5.0
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.vendor=Andrei Jiroh Halili
            # Docs will be written soon
            org.opencontainers.image.documentation=https://ajhalili2006.github.io/vaultwarden-on-paas-helpers

      # Then set up QEMU and Buildx so the Build and push action below will not trigger errors
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
